version: "2"

run:
  timeout: 3m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - asciicheck
    - bodyclose
    - misspell

  settings:
    gocritic:
      enabled-checks:
        - rangeValCopy
        - appendCombine

    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: empty-block
        - name: blank-imports
        - name: var-naming
        - name: error-naming
        - name: unexported-return
        - name: function-length
          arguments: [50, 25]
        - name: cognitive-complexity
          arguments: [15]
        - name: time-naming
