version: 2

run:
  timeout: 5m
  tests: true

issues:
  new: true
  new-from-rev: origin/main
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - asciicheck
    - bodyclose
    - misspell
    - deadcode
    - gosimple
    - stylecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - "(*os.File).Close"
      - "signal.Stop"
      - "os.Remove"
      - "fmt.Fprintf"
      - "fmt.Fprint"
      - "fmt.Fprintln"
      - "io.Copy"
      - "(*bytes.Buffer).Write"
      - "(*bytes.Buffer).ReadFrom"
      - "common.WriteHandshake"
      - "os.Setenv"
      - "github.com/spf13/pflag.FlagSet.Parse"
      - "github.com/spf13/viper.Viper.BindPFlags"
      - "hash.Hash.Write"
      - "golang.org/x/sys/unix.Close"
      - "(*strings.Builder).Write"
      - "(*lvmsync_go/dedup.Hasher).Write"

  gocritic:
    enabled-checks:
      - rangeValCopy
      - appendCombine

  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: empty-block
      - name: blank-imports
      - name: var-naming
      - name: error-naming
      - name: unexported-return
      - name: function-length
        arguments: [120, 100]
      - name: cognitive-complexity
        arguments: [15]
      - name: time-naming
