# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lvmsync_go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    gcflags:
      - all=-d=stripdebug=true
    ldflags:
      - -s -w -buildid= -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitDate }}"
    flags:
      - -trimpath

archives:
  - format: tar.gz
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - "examples/**"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    cmd: gpg
    args: ["--batch","--yes","--armor","--detach-sign","--output","${signature}","${artifact}"]
