# syntax=docker/dockerfile:1.4
# Dockerfile.distroless

# 1) Build
FROM golang:1.24-alpine AS build
ARG BIN
ARG BUILD_PATH=.
ARG GIT_SHA=unknown

RUN apk add --no-cache \
      build-base \
      linux-headers \
      pkgconf \
      lvm2-dev \
      libaio-dev

ENV CGO_ENABLED=1 \
    GO111MODULE=on

WORKDIR /src
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -ldflags "-s -w -X lvmsync_go/internal/config.BuildVersion=${GIT_SHA}" -o /out/${BIN} ${BUILD_PATH}

# 2) Runtime
FROM gcr.io/distroless/base-debian12:nonroot
ARG BIN
COPY --from=build /out/${BIN} /usr/local/bin/${BIN}
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/${BIN}"]
