// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/replication.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Replication_LockVolume_FullMethodName           = "/replication.Replication/LockVolume"
	Replication_GetVolumeMetadata_FullMethodName    = "/replication.Replication/GetVolumeMetadata"
	Replication_SendVolumeMetadata_FullMethodName   = "/replication.Replication/SendVolumeMetadata"
	Replication_StartTransferSession_FullMethodName = "/replication.Replication/StartTransferSession"
	Replication_FinalizeSync_FullMethodName         = "/replication.Replication/FinalizeSync"
	Replication_GetStatus_FullMethodName            = "/replication.Replication/GetStatus"
	Replication_Ping_FullMethodName                 = "/replication.Replication/Ping"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error)
	SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error)
	StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_LockVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeMetadata)
	err := c.cc.Invoke(ctx, Replication_GetVolumeMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_SendVolumeMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_StartTransferSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_FinalizeSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility.
type ReplicationServer interface {
	LockVolume(context.Context, *LockRequest) (*StatusResponse, error)
	GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error)
	SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error)
	StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error)
	FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error)
	GetStatus(context.Context, *LockRequest) (*StatusResponse, error)
	Ping(context.Context, *Empty) (*StatusResponse, error)
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServer struct{}

func (UnimplementedReplicationServer) LockVolume(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockVolume not implemented")
}
func (UnimplementedReplicationServer) GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransferSession not implemented")
}
func (UnimplementedReplicationServer) FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSync not implemented")
}
func (UnimplementedReplicationServer) GetStatus(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedReplicationServer) Ping(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}
func (UnimplementedReplicationServer) testEmbeddedByValue()                     {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	// If the following call pancis, it indicates UnimplementedReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_LockVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).LockVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_LockVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).LockVolume(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_SendVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_SendVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, req.(*VolumeMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_StartTransferSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).StartTransferSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_StartTransferSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).StartTransferSession(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_FinalizeSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).FinalizeSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_FinalizeSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).FinalizeSync(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetStatus(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockVolume",
			Handler:    _Replication_LockVolume_Handler,
		},
		{
			MethodName: "GetVolumeMetadata",
			Handler:    _Replication_GetVolumeMetadata_Handler,
		},
		{
			MethodName: "SendVolumeMetadata",
			Handler:    _Replication_SendVolumeMetadata_Handler,
		},
		{
			MethodName: "StartTransferSession",
			Handler:    _Replication_StartTransferSession_Handler,
		},
		{
			MethodName: "FinalizeSync",
			Handler:    _Replication_FinalizeSync_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Replication_GetStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Replication_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/replication.proto",
}
