// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/replication.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Replication_LockVolume_FullMethodName           = "/replication.Replication/LockVolume"
	Replication_GetVolumeMetadata_FullMethodName    = "/replication.Replication/GetVolumeMetadata"
	Replication_SendVolumeMetadata_FullMethodName   = "/replication.Replication/SendVolumeMetadata"
	Replication_StartTransferSession_FullMethodName = "/replication.Replication/StartTransferSession"
	Replication_FinalizeSync_FullMethodName         = "/replication.Replication/FinalizeSync"
	Replication_GetStatus_FullMethodName            = "/replication.Replication/GetStatus"
	Replication_Ping_FullMethodName                 = "/replication.Replication/Ping"
	Replication_Handshake_FullMethodName            = "/replication.Replication/Handshake"
	Replication_CreateSession_FullMethodName        = "/replication.Replication/CreateSession"
	Replication_SendResumeBitmap_FullMethodName     = "/replication.Replication/SendResumeBitmap"
	Replication_SendFinalManifest_FullMethodName    = "/replication.Replication/SendFinalManifest"
	Replication_Finalize_FullMethodName             = "/replication.Replication/Finalize"
	Replication_AckStream_FullMethodName            = "/replication.Replication/AckStream"
	Replication_Probe_FullMethodName                = "/replication.Replication/Probe"
	Replication_StartSync_FullMethodName            = "/replication.Replication/StartSync"
	Replication_Cancel_FullMethodName               = "/replication.Replication/Cancel"
	Replication_ProgressStream_FullMethodName       = "/replication.Replication/ProgressStream"
	Replication_BuildManifest_FullMethodName        = "/replication.Replication/BuildManifest"
	Replication_Verify_FullMethodName               = "/replication.Replication/Verify"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error)
	SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error)
	StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	SendResumeBitmap(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResumeBitmap, StatusResponse], error)
	SendFinalManifest(ctx context.Context, in *ManifestMessage, opts ...grpc.CallOption) (*StatusResponse, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	AckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ack, Ack], error)
	Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StartSync(ctx context.Context, in *StartSyncRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ProgressStream(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error)
	BuildManifest(ctx context.Context, in *BuildManifestRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_LockVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeMetadata)
	err := c.cc.Invoke(ctx, Replication_GetVolumeMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_SendVolumeMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_StartTransferSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_FinalizeSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, Replication_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, Replication_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) SendResumeBitmap(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResumeBitmap, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], Replication_SendResumeBitmap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResumeBitmap, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_SendResumeBitmapClient = grpc.ClientStreamingClient[ResumeBitmap, StatusResponse]

func (c *replicationClient) SendFinalManifest(ctx context.Context, in *ManifestMessage, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_SendFinalManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Finalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) AckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ack, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[1], Replication_AckStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ack, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_AckStreamClient = grpc.BidiStreamingClient[Ack, Ack]

func (c *replicationClient) Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) StartSync(ctx context.Context, in *StartSyncRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_StartSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) ProgressStream(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Progress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[2], Replication_ProgressStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressRequest, Progress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_ProgressStreamClient = grpc.ServerStreamingClient[Progress]

func (c *replicationClient) BuildManifest(ctx context.Context, in *BuildManifestRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_BuildManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility.
type ReplicationServer interface {
	LockVolume(context.Context, *LockRequest) (*StatusResponse, error)
	GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error)
	SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error)
	StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error)
	FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error)
	GetStatus(context.Context, *LockRequest) (*StatusResponse, error)
	Ping(context.Context, *Empty) (*StatusResponse, error)
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	CreateSession(context.Context, *SessionRequest) (*SessionResponse, error)
	SendResumeBitmap(grpc.ClientStreamingServer[ResumeBitmap, StatusResponse]) error
	SendFinalManifest(context.Context, *ManifestMessage) (*StatusResponse, error)
	Finalize(context.Context, *FinalizeRequest) (*StatusResponse, error)
	AckStream(grpc.BidiStreamingServer[Ack, Ack]) error
	Probe(context.Context, *ProbeRequest) (*StatusResponse, error)
	StartSync(context.Context, *StartSyncRequest) (*StatusResponse, error)
	Cancel(context.Context, *CancelRequest) (*StatusResponse, error)
	ProgressStream(*ProgressRequest, grpc.ServerStreamingServer[Progress]) error
	BuildManifest(context.Context, *BuildManifestRequest) (*StatusResponse, error)
	Verify(context.Context, *VerifyRequest) (*StatusResponse, error)
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServer struct{}

func (UnimplementedReplicationServer) LockVolume(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockVolume not implemented")
}
func (UnimplementedReplicationServer) GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransferSession not implemented")
}
func (UnimplementedReplicationServer) FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSync not implemented")
}
func (UnimplementedReplicationServer) GetStatus(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedReplicationServer) Ping(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedReplicationServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedReplicationServer) CreateSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedReplicationServer) SendResumeBitmap(grpc.ClientStreamingServer[ResumeBitmap, StatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendResumeBitmap not implemented")
}
func (UnimplementedReplicationServer) SendFinalManifest(context.Context, *ManifestMessage) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFinalManifest not implemented")
}
func (UnimplementedReplicationServer) Finalize(context.Context, *FinalizeRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedReplicationServer) AckStream(grpc.BidiStreamingServer[Ack, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method AckStream not implemented")
}
func (UnimplementedReplicationServer) Probe(context.Context, *ProbeRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedReplicationServer) StartSync(context.Context, *StartSyncRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSync not implemented")
}
func (UnimplementedReplicationServer) Cancel(context.Context, *CancelRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedReplicationServer) ProgressStream(*ProgressRequest, grpc.ServerStreamingServer[Progress]) error {
	return status.Errorf(codes.Unimplemented, "method ProgressStream not implemented")
}
func (UnimplementedReplicationServer) BuildManifest(context.Context, *BuildManifestRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildManifest not implemented")
}
func (UnimplementedReplicationServer) Verify(context.Context, *VerifyRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}
func (UnimplementedReplicationServer) testEmbeddedByValue()                     {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	// If the following call pancis, it indicates UnimplementedReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_LockVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).LockVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_LockVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).LockVolume(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_SendVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_SendVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, req.(*VolumeMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_StartTransferSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).StartTransferSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_StartTransferSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).StartTransferSession(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_FinalizeSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).FinalizeSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_FinalizeSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).FinalizeSync(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetStatus(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).CreateSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_SendResumeBitmap_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).SendResumeBitmap(&grpc.GenericServerStream[ResumeBitmap, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_SendResumeBitmapServer = grpc.ClientStreamingServer[ResumeBitmap, StatusResponse]

func _Replication_SendFinalManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).SendFinalManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_SendFinalManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).SendFinalManifest(ctx, req.(*ManifestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Finalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_AckStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).AckStream(&grpc.GenericServerStream[Ack, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_AckStreamServer = grpc.BidiStreamingServer[Ack, Ack]

func _Replication_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Probe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_StartSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).StartSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_StartSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).StartSync(ctx, req.(*StartSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_ProgressStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServer).ProgressStream(m, &grpc.GenericServerStream[ProgressRequest, Progress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_ProgressStreamServer = grpc.ServerStreamingServer[Progress]

func _Replication_BuildManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).BuildManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_BuildManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).BuildManifest(ctx, req.(*BuildManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockVolume",
			Handler:    _Replication_LockVolume_Handler,
		},
		{
			MethodName: "GetVolumeMetadata",
			Handler:    _Replication_GetVolumeMetadata_Handler,
		},
		{
			MethodName: "SendVolumeMetadata",
			Handler:    _Replication_SendVolumeMetadata_Handler,
		},
		{
			MethodName: "StartTransferSession",
			Handler:    _Replication_StartTransferSession_Handler,
		},
		{
			MethodName: "FinalizeSync",
			Handler:    _Replication_FinalizeSync_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Replication_GetStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Replication_Ping_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _Replication_Handshake_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Replication_CreateSession_Handler,
		},
		{
			MethodName: "SendFinalManifest",
			Handler:    _Replication_SendFinalManifest_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _Replication_Finalize_Handler,
		},
		{
			MethodName: "Probe",
			Handler:    _Replication_Probe_Handler,
		},
		{
			MethodName: "StartSync",
			Handler:    _Replication_StartSync_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Replication_Cancel_Handler,
		},
		{
			MethodName: "BuildManifest",
			Handler:    _Replication_BuildManifest_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Replication_Verify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendResumeBitmap",
			Handler:       _Replication_SendResumeBitmap_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AckStream",
			Handler:       _Replication_AckStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ProgressStream",
			Handler:       _Replication_ProgressStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/replication.proto",
}
