// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/replication.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Replication_LockVolume_FullMethodName           = "/replication.Replication/LockVolume"
	Replication_GetVolumeMetadata_FullMethodName    = "/replication.Replication/GetVolumeMetadata"
	Replication_SendVolumeMetadata_FullMethodName   = "/replication.Replication/SendVolumeMetadata"
	Replication_StartTransferSession_FullMethodName = "/replication.Replication/StartTransferSession"
	Replication_FinalizeSync_FullMethodName         = "/replication.Replication/FinalizeSync"
	Replication_GetStatus_FullMethodName            = "/replication.Replication/GetStatus"
	Replication_Ping_FullMethodName                 = "/replication.Replication/Ping"
	Replication_ExchangeCapabilities_FullMethodName = "/replication.Replication/ExchangeCapabilities"
	Replication_CreateSession_FullMethodName        = "/replication.Replication/CreateSession"
	Replication_SendResumeBitmap_FullMethodName     = "/replication.Replication/SendResumeBitmap"
	Replication_Finalize_FullMethodName             = "/replication.Replication/Finalize"
	Replication_AckStream_FullMethodName            = "/replication.Replication/AckStream"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error)
	SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error)
	StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	ExchangeCapabilities(ctx context.Context, in *CapabilitySet, opts ...grpc.CallOption) (*CapabilitySet, error)
	CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	SendResumeBitmap(ctx context.Context, opts ...grpc.CallOption) (Replication_SendResumeBitmapClient, error)
	Finalize(ctx context.Context, in *SessionResponse, opts ...grpc.CallOption) (*StatusResponse, error)
	AckStream(ctx context.Context, opts ...grpc.CallOption) (Replication_AckStreamClient, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) LockVolume(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_LockVolume_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetVolumeMetadata(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*VolumeMetadata, error) {
	out := new(VolumeMetadata)
	err := c.cc.Invoke(ctx, Replication_GetVolumeMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) SendVolumeMetadata(ctx context.Context, in *VolumeMetadata, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_SendVolumeMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) StartTransferSession(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_StartTransferSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) FinalizeSync(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_FinalizeSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) GetStatus(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) ExchangeCapabilities(ctx context.Context, in *CapabilitySet, opts ...grpc.CallOption) (*CapabilitySet, error) {
	out := new(CapabilitySet)
	err := c.cc.Invoke(ctx, Replication_ExchangeCapabilities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, Replication_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) SendResumeBitmap(ctx context.Context, opts ...grpc.CallOption) (Replication_SendResumeBitmapClient, error) {
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], Replication_SendResumeBitmap_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationSendResumeBitmapClient{stream}
	return x, nil
}

type Replication_SendResumeBitmapClient interface {
	Send(*ResumeBitmap) error
	CloseAndRecv() (*StatusResponse, error)
	grpc.ClientStream
}

type replicationSendResumeBitmapClient struct {
	grpc.ClientStream
}

func (x *replicationSendResumeBitmapClient) Send(m *ResumeBitmap) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicationSendResumeBitmapClient) CloseAndRecv() (*StatusResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationClient) Finalize(ctx context.Context, in *SessionResponse, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Replication_Finalize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) AckStream(ctx context.Context, opts ...grpc.CallOption) (Replication_AckStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[1], Replication_AckStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationAckStreamClient{stream}
	return x, nil
}

type Replication_AckStreamClient interface {
	Send(*StatusResponse) error
	Recv() (*StatusResponse, error)
	grpc.ClientStream
}

type replicationAckStreamClient struct {
	grpc.ClientStream
}

func (x *replicationAckStreamClient) Send(m *StatusResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicationAckStreamClient) Recv() (*StatusResponse, error) {
	m := new(StatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility
type ReplicationServer interface {
	LockVolume(context.Context, *LockRequest) (*StatusResponse, error)
	GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error)
	SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error)
	StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error)
	FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error)
	GetStatus(context.Context, *LockRequest) (*StatusResponse, error)
	Ping(context.Context, *Empty) (*StatusResponse, error)
	ExchangeCapabilities(context.Context, *CapabilitySet) (*CapabilitySet, error)
	CreateSession(context.Context, *SessionRequest) (*SessionResponse, error)
	SendResumeBitmap(Replication_SendResumeBitmapServer) error
	Finalize(context.Context, *SessionResponse) (*StatusResponse, error)
	AckStream(Replication_AckStreamServer) error
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (UnimplementedReplicationServer) LockVolume(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockVolume not implemented")
}
func (UnimplementedReplicationServer) GetVolumeMetadata(context.Context, *LockRequest) (*VolumeMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) SendVolumeMetadata(context.Context, *VolumeMetadata) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVolumeMetadata not implemented")
}
func (UnimplementedReplicationServer) StartTransferSession(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTransferSession not implemented")
}
func (UnimplementedReplicationServer) FinalizeSync(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSync not implemented")
}
func (UnimplementedReplicationServer) GetStatus(context.Context, *LockRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedReplicationServer) Ping(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedReplicationServer) ExchangeCapabilities(context.Context, *CapabilitySet) (*CapabilitySet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeCapabilities not implemented")
}
func (UnimplementedReplicationServer) CreateSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedReplicationServer) SendResumeBitmap(Replication_SendResumeBitmapServer) error {
	return status.Errorf(codes.Unimplemented, "method SendResumeBitmap not implemented")
}
func (UnimplementedReplicationServer) Finalize(context.Context, *SessionResponse) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedReplicationServer) AckStream(Replication_AckStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AckStream not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_LockVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).LockVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_LockVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).LockVolume(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetVolumeMetadata(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_SendVolumeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_SendVolumeMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).SendVolumeMetadata(ctx, req.(*VolumeMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_StartTransferSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).StartTransferSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_StartTransferSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).StartTransferSession(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_FinalizeSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).FinalizeSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_FinalizeSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).FinalizeSync(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).GetStatus(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_ExchangeCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitySet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).ExchangeCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_ExchangeCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).ExchangeCapabilities(ctx, req.(*CapabilitySet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).CreateSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_SendResumeBitmap_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).SendResumeBitmap(&replicationSendResumeBitmapServer{stream})
}

type Replication_SendResumeBitmapServer interface {
	SendAndClose(*StatusResponse) error
	Recv() (*ResumeBitmap, error)
	grpc.ServerStream
}

type replicationSendResumeBitmapServer struct {
	grpc.ServerStream
}

func (x *replicationSendResumeBitmapServer) SendAndClose(m *StatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicationSendResumeBitmapServer) Recv() (*ResumeBitmap, error) {
	m := new(ResumeBitmap)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Replication_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_Finalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).Finalize(ctx, req.(*SessionResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_AckStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).AckStream(&replicationAckStreamServer{stream})
}

type Replication_AckStreamServer interface {
	Send(*StatusResponse) error
	Recv() (*StatusResponse, error)
	grpc.ServerStream
}

type replicationAckStreamServer struct {
	grpc.ServerStream
}

func (x *replicationAckStreamServer) Send(m *StatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicationAckStreamServer) Recv() (*StatusResponse, error) {
	m := new(StatusResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockVolume",
			Handler:    _Replication_LockVolume_Handler,
		},
		{
			MethodName: "GetVolumeMetadata",
			Handler:    _Replication_GetVolumeMetadata_Handler,
		},
		{
			MethodName: "SendVolumeMetadata",
			Handler:    _Replication_SendVolumeMetadata_Handler,
		},
		{
			MethodName: "StartTransferSession",
			Handler:    _Replication_StartTransferSession_Handler,
		},
		{
			MethodName: "FinalizeSync",
			Handler:    _Replication_FinalizeSync_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Replication_GetStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Replication_Ping_Handler,
		},
		{
			MethodName: "ExchangeCapabilities",
			Handler:    _Replication_ExchangeCapabilities_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Replication_CreateSession_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _Replication_Finalize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendResumeBitmap",
			Handler:       _Replication_SendResumeBitmap_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AckStream",
			Handler:       _Replication_AckStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/replication.proto",
}
