#!/usr/bin/env bash
# check_release_artifacts.sh verifies that a GitHub release includes
# checksum and SBOM assets generated by GoReleaser.
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 <owner/repo> <tag>" >&2
  exit 1
fi

repo="$1"
tag="$2"

data=$(curl -fsSL "https://api.github.com/repos/${repo}/releases/tags/${tag}")
assets=$(echo "$data" | jq -r '.assets[].name')

if ! echo "$assets" | grep -q 'checksums.txt'; then
  echo "missing checksum artifact" >&2
  exit 1
fi

if ! echo "$assets" | grep -q '\.sbom'; then
  echo "missing SBOM artifact" >&2
  exit 1
fi

echo "release ${repo}@${tag} has SBOM and checksum artifacts"
